---
- name: Install Docker
  package:
    name: docker
    state: present

- name: Add ec2-user to the docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Fix permissions on Docker socket
  file:
    path: /var/run/docker.sock
    owner: ec2-user
    group: docker
    mode: '0660'
  become: yes

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started
