---
- name: Configure EC2 instances
  hosts: all
  become: yes
  vars:
    nginx_message: "{{ inventory_hostname }}"

  tasks:
    - name: Download CloudWatch Agent package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
        dest: /tmp/amazon-cloudwatch-agent.rpm

    - name: Install CloudWatch Agent
      yum:
        name: /tmp/amazon-cloudwatch-agent.rpm
        state: present

    - name: Create CloudWatch Agent Config File
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/lib/docker/containers/*/*.log",
                      "log_group_name": "/nginx/logs",
                      "log_stream_name": "{instance_id}"
                    }
                  ]
                }
              }
            }
          }

    - name: Start CloudWatch Agent
      command: >
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config
        -m ec2
        -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        -s

    - name: Install Docker
      package:
        name: docker
        state: present
        
    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Fix permissions on Docker socket
      command: chown ec2-user:docker /var/run/docker.sock
      become: yes

    - name: Create custom index.html for Nginx
      copy:
        dest: /tmp/index.html
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body><h1>Hello from {{ nginx_message }}</h1></body>
          </html>

    - name: Run Nginx container with custom index.html
      shell: |
        docker rm -f nginx || true
        docker run -d --name nginx -p 80:80 \
          -v /tmp/index.html:/usr/share/nginx/html/index.html:ro nginx
