---
- name: Configure EC2 instances
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Include CloudWatch Role
      include_role:
        name: cloudwatch

    - name: Include Docker Role
      include_role:
        name: docker

    - name: Include Nginx Role
      include_role:
        name: nginx
