- name: Configure EC2 instances with CloudWatch, Docker, and Nginx
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Include CloudWatch role
      include_role:
        name: cloudwatch

    - name: Include Docker role
      include_role:
        name: docker

    - name: Set private IPs for all Nginx servers
      run_once: true
      set_fact:
        private_ips: "{{ groups['nginx_servers'] | map('extract', hostvars, ['ansible_host']) | list }}"

    - name: Include Nginx role
      include_role:
        name: nginx


